### ISSUE TITLE
Can you add our work which is related to the molecular science / physics?

### ISSUE THREAD

**Issue by seongsukim-ml** [azminewasi/Awesome-Graph-Research-ICML2024#1]
First of all, thank you for sharing the compilation.

It was challenging to find works on the ICML official site, which was not user-friendly to navigate.

Our recent work, "Gaussian Plane-Wave Neural Operator for Electron Density Prediction," is also related to GNNs for capturing geometrical long-range interactions by considering the adopting the domain specific concept of the molecular science.

If possible, please consider adding our work to your compilation.

Thank you again.

[Gaussian Plane-Wave Neural Operator for Electron Density Prediction](https://openreview.net/forum?id=TvoG41N1Y3)

https://openreview.net/forum?id=TvoG41N1Y3

**Comment by azminewasi** [comment]
Thank you for notifying me. I've included it!
